version: '2'
services:
  movieinsights-app:
    image: movieinsights
    environment:
      - _JAVA_OPTIONS=-Xmx32g -Xms1g
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movieinsights-postgresql:5432/MovieInsights
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://movieinsights-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://movieinsights-elasticsearch:9200
    ports:
      - 8080:8080
  movieinsights-postgresql:
    extends:
      file: postgresql.yml
      service: movieinsights-postgresql
  movieinsights-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: movieinsights-elasticsearch
