version: '2'
services:
  movieinsights-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/MovieInsights/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=MovieInsights
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5432:5432
